### PR TITLE
Laravel 5.4 Shift

### PR DESCRIPTION
**Pull request by syropian**
This pull request includes the changes for upgrading to Laravel 5.4. Feel free to commit any additional changes to the `shift-2137` branch.

**Before merging**, you should:

- Checkout the `shift-2137` branch
- Review **all** pull request comments for additional changes
- Run `composer update` (if the pre-commands fail, add `--no-scripts`)
- Thoroughly test your application

If you would like more help with your upgrade, check out the [human services from Laravel Shift](https://laravelshift.com/human-services). And if you want to level-up your Git skills, check out [Getting Git](https://gettinggit.com).

### CODE REVIEW

**Comment by syropian** [comment]
ℹ Laravel 5.4 added new middleware to handle whitespace in request data. This may affect the data your application received. Read this [post on Laravel News](https://laravel-news.com/laravel-5-4-middleware) for more detail to see if you need to modify your application.

**Comment by syropian** [comment]
❌ I was not able to update your `app/Providers/BroadcastServiceProvider.php`. You will need to compare yours against the [5.4 version](https://github.com/laravel-shift/laravel-5.4/blob/master/app/Providers/BroadcastServiceProvider.php) and merge any new changes.

**Comment by syropian** [comment]
❌ I could not upgrade the following project files since they differed from the default Laravel version. You need to compare these project files against the [default Laravel 5.4 versions](https://github.com/laravel-shift/laravel-5.4/) and merge any changes:

- [ ] package.json
- [ ] resources/assets/js/bootstrap.js
- [ ] gulpfile.js

**Comment by syropian** [comment]
❌ I could not upgrade the following configuration files since they differed from the default Laravel version. You need to compare these configuration files against the [Laravel 5.4 configuration files](https://github.com/laravel-shift/laravel-5.4/blob/master/config) and merge any changes:

- [ ] config/cache.php
- [ ] config/database.php
- [ ] config/filesystems.php

**Comment by syropian** [comment]
⚠ It looks like you have some custom tests. Laravel 5.4's testing layer has been re-written. You should review the *Testing* section of the [Upgrade Guide](https://laravel.com/docs/5.4/upgrade#upgrade-5.4.0) to determine if you want to upgrade your tests (recommended) or run them with the Laravel 5.3 testing layer.

**Comment by syropian** [comment]
ℹ In Laravel 5.4, the *date* cast creates a Carbon object which calls `startOfDay`. If you need to preserve the time portion of the *date*, you should use the *datetime* cast or convert your column to a `datetime`. Review the documentation on [Attribute Casting](https://laravel.com/docs/5.4/eloquent-mutators#attribute-casting) for more details.

**Comment by syropian** [comment]
ℹ Laravel 5.4 no longer includes the ability to customize the PDO "fetch style". Now `PDO::FETCH_OBJ` is always used. If you need to customize the fetch style, check the *Database* section of the [Upgrade Guide](https://laravel.com/docs/5.4/upgrade#upgrade-5.4.0) for more details.

**Comment by syropian** [comment]
ℹ If you have manually upgraded your app for previous versions of Laravel, I recommend running the [Laravel Linter](https://laravelshift.com/laravel-linter) to ensure your app is fully upgraded to the latest version of Laravel.

**Comment by syropian** [comment]
@alexbowers If you have any spare time could you take a look at this? Looks like the required changes are fairly minor.

**Comment by alexbowers** [comment]
@syropian I think this is done. Any chance you can do some testing on it?

you'll need to run these scripts:

`composer update --no-scripts`
`composer update`

**Comment by syropian** [comment]
@alexbowers Thanks! Just did some testing locally and everything seems to be in working order. Going to merge and deploy this, I'll keep an eye on the support email account just in case.

**Pull request merged**
