### PR TITLE
UpdatedAt predicates

### PR DESCRIPTION
**Pull request by tomershvueli**
Added a filter for the `pushedAt` value for Stars. 

- Brought in vue2-datepicker
- Created DateFilter
- Be sure to pass tests after importing CSS files (__mocks__/styleMock.js file)

image

I'm wondering if there's any sort of 'sort' mechanism on these lists? I'm not seeing it right now, but am seeing older comments reference sorting - is this something that was removed? If it were still in place, this would be good to add, i.e. 'Sort by repos that were updated most recently'.

### CODE REVIEW

**Comment by syropian** [comment]
Thanks! I'll take a closer look at this in the next couple days. 

There's currently no sorting for the stars list, just the tags. It's something I've been meaning to add for a long time, but now that this stuff is making its way in it gives me a good reason to actually prioritize it 😅

**Comment by tomershvueli** [comment]
@syropian any update on this? My Vue can't be that bad, can it? 😅

**Review by syropian — APPROVED** [review]
@tomershvueli Sorry for the delay! Had a busy week, and haven't been feeling the greatest. This lg2m 👍🏻

**Comment by tomershvueli** [comment]
@syropian thanks! Hope you feel better soon!

**Pull request merged**
