### PR TITLE
implement sweetalert

### PR DESCRIPTION
**Pull request by bntzio**
I just implemented SweetAlert into Astral 😄 

When you delete a tag, instead of showing the default browser confirm prompt, it now appears a nice good-looking confirmation modal.

Are there other cases of browser prompts or alerts like this one?

### CODE REVIEW

**Comment by syropian** [comment]
Thanks! I'll take a closer look at this after I'm off work. 

Cheers!

**Comment by bntzio** [comment]
@syropian yeah that's another way to do it (and much cleaner)! 👍 

Now, for the sass `@import` in `app.scss` would you like me to import the scss version of the sweetalert as well as the theme? Or the css one? I think both work well, but the scss version is a better approach, what do you think?

**Comment by syropian** [comment]
@bntzio scss is fine :)

**Comment by syropian** [comment]
@bntzio Oh, also make sure to run `npm production` and commit those changes as well. Thanks! 🙏

**Comment by bntzio** [comment]
@syropian done! 😄

**Comment by syropian** [comment]
Merged and deployed to production :)

**Pull request merged**
