### PR TITLE
Readme not found

### PR DESCRIPTION
**Pull request by alexbowers**
Some bugs that need your work.

image

image

### CODE REVIEW

**Comment by syropian** [comment]
Thanks, I should be able to get to this early this week.

**Comment by syropian** [comment]
@alexbowers How did you get that visual bug? I tried:

1) Choose repo
2) Open tag dropdown
3) Choose repo that has no readme

When I choose the no-readme repo it closed the tag field.

**Comment by alexbowers** [comment]
Its the other way around. Go to a repo without a readme and just click "Edit tags"

**Comment by alexbowers** [comment]
There are two issues:

1) The transparent overlay makes a readme visible from the past on a new repo without a readme.

To replicate:

Open a repo with a readme, then go to a repo without a readme.

2) The edit tags is behind the transparent overlay

To replicate:

Open a repo without a readme, and click on edit tags.

**Comment by alexbowers** [comment]
Still a bug: 

image

**Comment by syropian** [comment]
Whoops, forgot to make it fully solid.

**Pull request merged**
